### ISSUE TITLE
EmptyClause when no empty clause in input.

### ISSUE THREAD

**Issue by sirandreww** [shnarazk/splr#193]
I'm using this crate for SAT solving with a library I'm writing for formal verification algorithm development.
I'm giving SPLR the following input:
[[4, -5], [-3], [-3, -4], [1, -4, 5], [-1], [-2, -4], [2, 3, 4], [-2], [-1, -5], [3]]
And I'm getting an error about empty clause?

This is where the error originates:
![image](https://user-images.githubusercontent.com/49692450/197565417-15a93504-6722-4e8c-962f-0ad5a71b9b88.png)

This is how I'm calling the function:
![image](https://user-images.githubusercontent.com/49692450/197565661-202b116b-597e-4eb3-8a94-713cb83b8dd6.png)

I'm using splr = "0.16.3"
Am I doing something wrong?

**Comment by shnarazk** [comment]
@sirandreww 
Hi. Splr's `Solver` reads a given CNF like:

```rust
for c in cnf.iter_mut() {
  if c contains asserted literals(s) {
     continue;
  }
  if c contains negated literal(s) {
     remove all negated literals from c;  // [3] => []
  }
  match c.len() {
    0 => return Err(...), // Solver can't hold an empty clause in its internal DBs
    1 => add c[0] to assertion DB,
    _ => store c into clause DB,
  }
}
```

So the last clause `[3]` is identical to an empty clause after reading the 2nd clause `[-3]`. This is the reason.

Note: This is inconvinient: this CNF should be evaluated as `Ok(UNSAT)` instead of `Err(EmptyClause)`. In the upcomming Splr 0.17, `Certificate::try_from(cnf: Vec<Vec<i32>>>)` will return `Ok(UNSAT)` in this case, while `Solver::try_from(...)` still return an error.
